/** @type {import('tailwindcss').Config} */
export default {
    // purge: {
    //     content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
    //     safelist: [
    //         {
    //             pattern:
    //                 /^(gap|col-span|xs:col-span|sm:col-span|md:col-span|lg:col-span|xl:col-span)-[0-9]+$/,
    //             variants: ['xs', 'sm', 'md', 'lg', 'xl'],
    //         },
    //     ],
    // },
    purge: {
        content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
        safelist: [
            'gap-0',
            'gap-0.5',
            'gap-1',
            'gap-1.5',
            'gap-2',
            'gap-2.5',
            'gap-3',
            'gap-3.5',
            'gap-4',
            'gap-5',
            'gap-6',
            'gap-7',
            'gap-8',
            'gap-9',
            'gap-10',
            'gap-11',
            'gap-12',
            'gap-14',
            'gap-16',
            'gap-20',
            'gap-24',
            'gap-28',
            'gap-32',
            'gap-36',
            'gap-40',
            'gap-44',
            'gap-48',
            'gap-52',
            'gap-56',
            'gap-60',
            'gap-64',
            'gap-72',
            'gap-80',
            'gap-96',

            'col-span-1',
            'col-span-2',
            'col-span-3',
            'col-span-4',
            'col-span-5',
            'col-span-6',
            'col-span-7',
            'col-span-8',
            'col-span-9',
            'col-span-10',
            'col-span-11',
            'col-span-12',
            'xs:col-span-1',
            'xs:col-span-2',
            'xs:col-span-3',
            'xs:col-span-4',
            'xs:col-span-5',
            'xs:col-span-6',
            'xs:col-span-7',
            'xs:col-span-8',
            'xs:col-span-9',
            'xs:col-span-10',
            'xs:col-span-11',
            'xs:col-span-12',
            'sm:col-span-1',
            'sm:col-span-2',
            'sm:col-span-3',
            'sm:col-span-4',
            'sm:col-span-5',
            'sm:col-span-6',
            'sm:col-span-7',
            'sm:col-span-8',
            'sm:col-span-9',
            'sm:col-span-10',
            'sm:col-span-11',
            'sm:col-span-12',
            'md:col-span-1',
            'md:col-span-2',
            'md:col-span-3',
            'md:col-span-4',
            'md:col-span-5',
            'md:col-span-6',
            'md:col-span-7',
            'md:col-span-8',
            'md:col-span-9',
            'md:col-span-10',
            'md:col-span-11',
            'md:col-span-12',
            'lg:col-span-1',
            'lg:col-span-2',
            'lg:col-span-3',
            'lg:col-span-4',
            'lg:col-span-5',
            'lg:col-span-6',
            'lg:col-span-7',
            'lg:col-span-8',
            'lg:col-span-9',
            'lg:col-span-10',
            'lg:col-span-11',
            'lg:col-span-12',
            'xl:col-span-1',
            'xl:col-span-2',
            'xl:col-span-3',
            'xl:col-span-4',
            'xl:col-span-5',
            'xl:col-span-6',
            'xl:col-span-7',
            'xl:col-span-8',
            'xl:col-span-9',
            'xl:col-span-10',
            'xl:col-span-11',
            'xl:col-span-12',
        ],
    },
    content: [
        './index.html',
        './src/**/*.{js,ts,jsx,tsx}',
        './.storybook/**/*.{js,ts,jsx,tsx}',
        './public/index.html',
    ],
    theme: {
        container: {
            center: true,
        },
        extend: {
            colors: {
                primary: {
                    DEFAULT: '#4361ee',
                    light: '#eaf1ff',
                    'dark-light': 'rgba(67,97,238,.15)',
                },
                secondary: {
                    DEFAULT: '#805dca',
                    light: '#ebe4f7',
                    'dark-light': 'rgb(128 93 202 / 15%)',
                },
                success: {
                    DEFAULT: '#00ab55',
                    light: '#ddf5f0',
                    'dark-light': 'rgba(0,171,85,.15)',
                },
                danger: {
                    DEFAULT: '#e7515a',
                    light: '#fff5f5',
                    'dark-light': 'rgba(231,81,90,.15)',
                },
                warning: {
                    DEFAULT: '#e2a03f',
                    light: '#fff9ed',
                    'dark-light': 'rgba(226,160,63,.15)',
                },
                info: {
                    DEFAULT: '#2196f3',
                    light: '#e7f7ff',
                    'dark-light': 'rgba(33,150,243,.15)',
                },
                dark: {
                    DEFAULT: '#3b3f5c',
                    light: '#eaeaec',
                    'dark-light': 'rgba(59,63,92,.15)',
                },
                black: {
                    DEFAULT: '#0e1726',
                    light: '#e3e4eb',
                    'dark-light': 'rgba(14,23,38,.15)',
                },
                white: {
                    DEFAULT: '#ffffff',
                    light: '#e0e6ed',
                    dark: '#888ea8',
                },
            },
            fontFamily: {
                nunito: ['var(--font-nunito)'],
            },
            spacing: {
                4.5: '18px',
            },
            boxShadow: {
                '3xl': '0 2px 2px rgb(224 230 237 / 46%), 1px 6px 7px rgb(224 230 237 / 46%)',
            },
            typography: ({ theme }) => ({
                DEFAULT: {
                    css: {
                        '--tw-prose-invert-headings':
                            theme('colors.white.dark'),
                        '--tw-prose-invert-links': theme('colors.white.dark'),
                        h1: {
                            fontSize: '40px',
                            marginBottom: '0.5rem',
                            marginTop: 0,
                        },
                        h2: {
                            fontSize: '32px',
                            marginBottom: '0.5rem',
                            marginTop: 0,
                        },
                        h3: {
                            fontSize: '28px',
                            marginBottom: '0.5rem',
                            marginTop: 0,
                        },
                        h4: {
                            fontSize: '24px',
                            marginBottom: '0.5rem',
                            marginTop: 0,
                        },
                        h5: {
                            fontSize: '20px',
                            marginBottom: '0.5rem',
                            marginTop: 0,
                        },
                        h6: {
                            fontSize: '16px',
                            marginBottom: '0.5rem',
                            marginTop: 0,
                        },
                        p: { marginBottom: '0.5rem' },
                        li: { margin: 0 },
                        img: { margin: 0 },
                    },
                },
            }),
        },
    },
    plugins: [],
};
